development:
  host: localhost
  database: ShoppingCenter_development

test:
  host: localhost
  database: ShoppingCenter_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
