#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require 'resque/tasks'
require 'resque_scheduler/tasks'
require 'resque'

Dir['lib/modules/*.rb'].each { |mod| load(mod) }
Dir['lib/tasks/*.rake'].each { |file| load(file) }

require File.expand_path('../config/application', __FILE__)

task :console => :environment do
  sh "irb -rubygems -I config -r setup.irb.rb"
end

ShoppingCenter::Application.load_tasks
